---
- hosts: localhost
  connection: local
  vars:
    user_home: "/home/carlos"
    user_name: "carlos"
  become: yes

  tasks:
    - name: Install packages
      package:
        name: 
          - htop
          - tmux
          - neovim
          - i3
          - polybar
          - cmatrix

    - name: Copy bashrc
      copy:
        src: files/bashrc
        dest: "{{ user_home }}/.bashrc"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Copy i3 config
      copy:
        src: files/i3
        dest: "{{ user_home }}/.config/"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Copy polybar config
      copy:
        src: files/polybar
        dest: "{{ user_home }}/.config/"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Copy nvim config
      copy:
        src: files/nvim
        dest: "{{ user_home }}/.config/"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Add Ansible user
      user:
        name: ansible
        system: yes

    - name: Add Ansible user to sudoers
      copy:
        src: files/sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: Add Ansible-pull cron job
      cron:
        name: "Ansible-pull cron job"
        user: ansible
        minute: "*/10"
        job: "ansible-pull -o -U https://github.com/cgracia/ansible_desktop.git >> /var/log/ansible_dotfiles.log 2>&1"

    - name: Configure logrotate for ansible_dotfiles.log
      copy:
        src: files/logrotate_ansible_dotfiles
        dest: /etc/logrotate.d/ansible_dotfiles
        owner: root
        group: root
        mode: 0644
