---
- hosts: localhost
  connection: local
  become: no
  vars:
    #TODO: Add a way to set the user name and home directory
    user_home: "/home/carlos"
    user_name: "carlos"

  pre_tasks:
    - name: Include host-specific configuration
      include_vars: "host_vars/{{ ansible_hostname }}.yml"
      ignore_errors: yes

    - name: Include configuration file specified in host_vars
      include_vars: "{{ config_file }}"
      when: config_file is defined

    - debug:
        msg: "desktop_setup value: {{ desktop_setup | default('undefined') }}"

  roles:
    - role: desktop
      when: desktop_setup | default(false)

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - tmux
        state: present
        update_cache: yes
      become: yes

    - name: Create a universally accessible log directory
      ansible.builtin.file:
        path: /var/applogs
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: yes

    - name: Configure logrotate for applogs.log
      ansible.builtin.copy:
        src: files/logrotate_applogs
        dest: /etc/logrotate.d/applogs
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Add Ansible user
      ansible.builtin.user:
        name: ansible
        system: yes
      become: yes

    - name: Add Ansible user to sudoers
      ansible.builtin.copy:
        src: files/sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: '0440'
      become: yes

    - name: Add Ansible-pull cron job
      ansible.builtin.cron:
        name: "Ansible-pull cron job"
        user: ansible
        minute: "*/10"
        job: "sudo bash -c 'ansible-pull -o -U https://github.com/cgracia/ansible_desktop.git >> /var/applogs/ansible_dotfiles.log 2>&1'"
      become: yes
