---
- hosts: localhost
  connection: local
  vars:
    user_home: "/home/carlos"
    user_name: "carlos"
  become: yes

  tasks:
    - name: Add PPAs
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - "ppa:neovim-ppa/unstable"
        - "ppa:aslatter/ppa"

    - name: Install packages
      package:
        name: 
          - htop
          - tmux
          - neovim
          - i3
          - i3lock
          - i3lock-fancy
          - polybar
          - cmatrix
          - xss-lock
          - alacritty

    - name: Copy bashrc
      copy:
        src: files/bashrc
        dest: "{{ user_home }}/.bashrc"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Copy config files
      copy:
        src: files/config/
        dest: "{{ user_home }}/.config/"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Create a universally accessible log directory
      file:
        path: /var/applogs
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure logrotate for applogs.log
      copy:
        src: files/logrotate_applogs
        dest: /etc/logrotate.d/applogs
        owner: root
        group: root
        mode: 0644

    - name: Add Ansible user
      user:
        name: ansible
        system: yes

    - name: Add Ansible user to sudoers
      copy:
        src: files/sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: Add Ansible-pull cron job
      cron:
        name: "Ansible-pull cron job"
        user: ansible
        minute: "*/10"
        job: "sudo bash -c 'ansible-pull -o -U https://github.com/cgracia/ansible_desktop.git >> /var/applogs/ansible_dotfiles.log 2>&1'"

    - name: Check if Hack Nerd Font is already installed
      ansible.builtin.stat:
        path: /usr/share/fonts/Hack/HackNerdFont-Regular.ttf
      register: hack_font

    - name: Add fonts if needed
      include_tasks: tasks/fonts.yml
      when: not hack_font.stat.exists
