---
- name: Create fonts directory if it does not exist
  ansible.builtin.file:
    path: /usr/share/fonts/Hack
    state: directory
    mode: '0755'

- name: Download Hack Nerd Fonts zip file
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip
    dest: /tmp/Hack.zip
    mode: '0644'

- name: Unzip Hack Nerd Fonts to the fonts directory
  ansible.builtin.unarchive:
    src: /tmp/Hack.zip
    dest: /usr/share/fonts/Hack
    remote_src: yes

- name: Update font cache
  ansible.builtin.command:
    cmd: fc-cache -fv
