---
- name: Decrypt all secrets and deploy them to ~/.secrets
  hosts: localhost
  gather_facts: yes
  vars:
    vault_password_file: "~/.secrets/ansible_vault_pass"
    secrets_source_dir: "{{ playbook_dir }}/../files/secrets"
    secrets_dest_dir: "{{ ansible_env.HOME }}/.secrets"
  tasks:
    - name: Ensure the destination secrets directory exists
      file:
        path: "{{ secrets_dest_dir }}"
        state: directory
        mode: '0700'

    - name: Find all files in the secrets source directory
      find:
        paths: "{{ secrets_source_dir }}"
        file_type: file
      register: secrets_files

    - name: Decrypt each secret file using ansible-vault
      command: >
        ansible-vault view --vault-password-file {{ vault_password_file }} {{ item.path }}
      register: vault_results
      loop: "{{ secrets_files.files }}"
      changed_when: false

    - name: Write the decrypted content to the destination directory
      copy:
        dest: "{{ secrets_dest_dir }}/{{ item.item.path | basename }}"
        content: "{{ item.stdout }}"
        mode: '0600'
      loop: "{{ vault_results.results }}"
